### ISSUE TITLE
NSURLProtocol

### ISSUE THREAD

**Issue by BaiCanLin** [Countly/countly-sdk-ios#93] opened 2016-08-15 09:32 UTC
This sdk with a custom NSURLProtocol conflict, use only one

**Comment by BaiCanLin** [comment] 2016-08-15 09:33
#import "BCCustomURLProtocol.h"

static NSString * const BCURLProtocolHandledKey = @"BCURLProtocolHandledKey";

@interface BCCustomURLProtocol ()<NSURLConnectionDelegate>

@property (nonatomic, strong) NSURLConnection *connection;

@end

@implementation BCCustomURLProtocol

+ (BOOL)canInitWithRequest:(NSURLRequest *)request
{
//    NSLog(@"request %@",request);
    //只处理http和https请求
    NSString *scheme = [[request URL] scheme];
    if ( ([scheme caseInsensitiveCompare:@"http"] == NSOrderedSame ||
          [scheme caseInsensitiveCompare:@"https"] == NSOrderedSame))
    {
        //看看是否已经处理过了，防止无限循环
        if ([NSURLProtocol propertyForKey:BCURLProtocolHandledKey inRequest:request]) {
            return NO;
        }
        
        return YES;
    }
    return NO;
}

+ (NSURLRequest *)canonicalRequestForRequest:(NSURLRequest *)request {
    NSMutableURLRequest *mutableReqeust = [request mutableCopy];
    mutableReqeust = [self redirectHostInRequset:mutableReqeust];
    return mutableReqeust;
}

+ (BOOL)requestIsCacheEquivalent:(NSURLRequest *)a toRequest:(NSURLRequest *)b
{
    return [super requestIsCacheEquivalent:a toRequest:b];
}

- (void)startLoading
{
//    NSLog(@"startLoading = %@",[NSDate date]);
    
    NSMutableURLRequest *mutableReqeust = [[self request] mutableCopy];
    
    //打标签，防止无限循环
    [NSURLProtocol setProperty:@YES forKey:BCURLProtocolHandledKey inRequest:mutableReqeust];
    
    self.connection = [NSURLConnection connectionWithRequest:mutableReqeust delegate:self];
}

- (void)stopLoading
{
//    NSLog(@"stopLoading = %@",[NSDate date]);
    [self.connection cancel];
}

#pragma mark - NSURLConnectionDelegate

- (void) connection:(NSURLConnection *)connection didReceiveResponse:(NSURLResponse *)response {
    [self.client URLProtocol:self didReceiveResponse:response cacheStoragePolicy:NSURLCacheStorageNotAllowed];
}

- (void)connection:(NSURLConnection *)connection didReceiveData:(NSData *)data {
    [self.client URLProtocol:self didLoadData:data];
}

- (void)connectionDidFinishLoading:(NSURLConnection *)connection {
    
    [self.client URLProtocolDidFinishLoading:self];
}

- (void)connection:(NSURLConnection *)connection didFailWithError:(NSError *)error {
    [self.client URLProtocol:self didFailWithError:error];
}

+(NSMutableURLRequest*)redirectHostInRequset:(NSMutableURLRequest*)request
{
    if ([request.URL host].length == 0) {
        return request;
    }
    
    NSString *originUrlString = [request.URL absoluteString];
    NSString *originHostString = [request.URL host];
    NSRange hostRange = [originUrlString rangeOfString:originHostString];
    if (hostRange.location == NSNotFound) {
        return request;
    }
    
    NSLog(@"拦截到的URL===%@",[request.URL host]);
//    NSLog(@"lanjie URL===%@",request.URL.description);
    return request;
}

@end

**Comment by erkanyildiz** [comment] 2016-08-15 10:39
Can you explain what this is?

**Comment by BaiCanLin** [comment] 2016-08-15 15:54
@erkanyildiz NSURLProtocol custom

**Comment by erkanyildiz** [comment] 2016-08-16 02:59
I mean the issue. Can you explain what kind of problem you experience and why do you think it has  something to do with Countly SDK?

**Comment by BaiCanLin** [comment] 2016-08-16 03:36
Use NSURLProtocol UIWebView loading, UIWebView loading out

**Comment by erkanyildiz** [comment] 2016-08-16 04:38
Duplicate of #82

**Closed by erkanyildiz** 2016-08-16 04:38 UTC
