### ISSUE TITLE
Removing view tracking consent does not stop timer of last tracked view

### ISSUE THREAD

**Issue by felixmusmann** [Countly/countly-sdk-ios#172] opened 2020-11-19 10:35 UTC
### Expected Behavior

If the consent for view tracking is canceled, the tracking of the last view should stop.

### Current Behavior

Removing the consent for view tracking only has the effect, that new recordView calls are ignored. The timer is only stopped, when the consent is reenabled and a new view is recorded. This leads to a visitation with a duration that is too high.

### Steps to Reproduce (for bugs)

1. Give consent for view tracking.
2. Start tracking a view.
3. Cancel consent for view tracking.
4. Wait some time.
5. Give consent for view tracking.
6. Start tracking a view.

**Comment by erkanyildiz** [comment] 2020-11-23 08:24
Thanks for informing us about this issue. 

Issue is actually caused by these lines: 
https://github.com/Countly/countly-sdk-ios/blob/master/CountlyViewTracking.m#L205-L206

When consent for view tracking is cancelled, state clean up is only done if auto view tracking was enabled on initial configuration. This causes view tracking state information to be kept for manual view tracking case.

Problem should be fixed by removing that early return.

This fix will be a part of our next minor release.

Thank you very much again.

**Comment by erkanyildiz** [comment] 2020-12-05 09:48
https://github.com/erkanyildiz/countly-sdk-ios/commit/d147a9876a04797a8cb8f0f1f14ebeb2aab46402

This will be merged into main repo soon. Thanks.

**Closed by erkanyildiz** 2020-12-05 09:48 UTC
