### ISSUE TITLE
Limit stored data size if server is not reachable

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-ios#68] opened 2015-12-18 08:38 UTC
Limit data if server is not reachable for all SDKs, including Android (@iartem)

Should also be a part of SDK development guide (@ar2rsawseen)

**Comment by ar2rsawseen** [comment] 2015-12-18 08:41
Can you elaborate on reason and maybe even have some suggested limit in mind in terms of number of records or Kb?

**Comment by gorkem-cetin** [comment] 2015-12-18 08:54
It was reported via support that sending 600Kb data creates problems. This data has populated because server was down. Talked to Artem & thought it would be a good idea to have a limit, however cannot suggest anything at this moment.

**Comment by ar2rsawseen** [comment] 2015-12-18 08:59
Hmm, who would send 600Kb of data? You mean storing and retrieving it caused problems?

**Comment by gorkem-cetin** [comment] 2015-12-18 09:04
It wasnt meant to send 600K data at once. This much data has aggregated due to non functioning server.  Sending this data caused problems.

**Comment by erkanyildiz** [comment] 2016-01-14 16:34
I think here the problem is not the data size but the number of queued requests. As an average request is roughly 200 bytes, 600KB of data means around 3000 queued requests. So it might take quite some time to deliver them all to server, and new requests only keep stacking up in the queue.

Maybe we can add a manual flush method for deleting all the previously queued requests? So it would be up to developer. Or we can just check number of queued requests instead of data size?

**Comment by erkanyildiz** [comment] 2016-02-19 17:55
As we have not decided how to go yet, I close this issue and create a backlog card on jira.

**Closed by erkanyildiz** 2016-02-19 17:55 UTC
